version: "3"
services:
  backend:
    build: .
    image: ligapay
    container_name: ligapay-backend
    ports:
      - "4000:4000"
    volumes:
      - "./:/app"
    depends_on:
      - prisma
    environment:
      NODE_ENV: "development"

  prisma:
    image: "prismagraphql/prisma:1.32.2"
    container_name: ligapay-prisma
    restart: always
    ports:
      - 4466
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            rawAccess: true
            migrations: true

  postgres:
    image: postgres:11.3-alpine
    container_name: ligapay-db
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - /var/lib/postgresql/data

  pgadmin:
    image: "dpage/pgadmin4"
    container_name: ligapay-pgadmin
    depends_on:
      - postgres
    ports:
      - "80:80"
    volumes:
      - /var/lib/pgadmin
      - /pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ligapay"
      PGADMIN_DEFAULT_PASSWORD: "ligapay"
